AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Template to build required infra for an AWS Native CI/CD pipeline

Resources:

  PipelineS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::Region}-pipeline-artifacts
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  LambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::Region}-lambda-code
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3BucketForAwsCodepipelineArtifacts:
    Description: The bucket for holding ouu app's lambda code
    Value: !Ref PipelineS3Bucket
  S3BucketForAppLambdaPackages:
    Description: The bucket for holding ouu app's lambda code
    Value: !Ref LambdaS3Bucket
